### ISSUE TITLE
Carthage integration

### ISSUE THREAD

**Issue by arcturus** [bugfender/BugfenderSDK-iOS#18]
Could it be possible to add Carthage integration to the project?

**Comment by jgimenez** [comment]
Hi @arcturus, we have this in our roadmap but not ready yet. We're open to pull requests if you want to contribute it.

**Comment by jgimenez** [comment]
Carthage currently doesn't support shipping closed-source binaries. See Carthage/Carthage#1308.

**Comment by akolov** [comment]
Carthage supports binary only distributions already, could you support it please?
https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification

**Comment by jgimenez** [comment]
Hi @akolov, Chartage does support binary distribution, but does not support all the required project configuration that CocoaPods does automatically. Please follow the manual installation steps instead.

**Comment by jgimenez** [comment]
Unfortunately Carthage still does not allow us to configure all what's required for Swift support. We might start supporting Carthage once Swift has a [stable ABI](https://swift.org/abi-stability/).

**Comment by akolov** [comment]
What's the difference between manual installation by downloading zip archive with Bugfender and providing binary-only installation via Carthage?

**Comment by akolov** [comment]
Thank you for the clarificatino, @jgimene! 
I guess I never imported the swift file you mentioned, since I use SwiftyBeaver as a front-end for Bugfender. In this use case I only needed binary SDK itself, without helper functions.

**Comment by jgimenez** [comment]
Yes, probably in that case you could use the ZIP files we upload for every release

**Comment by codeslubber** [comment]
What are people doing about this? in 2019, having to constantly manually download and apply updates makes me want to delete the library immediately. This problem was solved a decade and a half ago.

**Comment by RubenVot** [comment]
Hi @codeslubber, as mentioned in the thread, Carthage integration was still not possible. Most of our users are using Cocoapods but we definitely have Carthage in our roadmap.

**Comment by jgimenez** [comment]
This is a nice article explaining **module stability**, which is what we need to distribute a compiled `BugfenderSDK.framework` with Swift support. Unfortunately it looks like it won't be released in Swift 5 yet.

**Comment by jgimenez** [comment]
Actually after having a second look (sorry, last time I checked was ages ago), it looks like installing Bugfender with Carthage would be 99% like the manual installation, just Carthage can download the framework file for you, which is already an advantage because you get updates, etc.

Adding support for Swift can be done at a later stage, when module stability is released.

I wrote the installation instructions in 99384f5
