### ISSUE TITLE
BFStorageItem.m line 631 -[BFStorageItem bf_sendLogsForSessionId:batchSize:withCompletionBlock:]

### ISSUE THREAD

**Issue by r-a-o** [bugfender/BugfenderSDK-iOS#41]
SDK version number: 1.6.2 & Bitcode disabled.

> BFStorageItem.m line 631 -[BFStorageItem bf_sendLogsForSessionId:batchSize:withCompletionBlock:]
> NSOperationQueue 0x28120e8e0 (QOS: UNSPECIFIED) EXC_BAD_ACCESS KERN_INVALID_ADDRESS
> 

Other similar crashes at line 449, 634, 741:

> BFStorageItem.m line 449
> __41-[BFStorageItem sendWithCompletionBlock:]_block_invoke

> BFStorageItem.m line 634
> -[BFStorageItem bf_sendLogsForSessionId:batchSize:withCompletionBlock:]
> 

> BFStorageItem.m line 741
> -[BFStorageItem bf_sendLogsAndWait:error:]

I am seeing a lot of these crashes on our app lately, the crash is not device or os specific, its spread over all devices and all OS version that we support (10, 11, 12)

Crashlytics Insights suggests that this is a Heap Corruption. 
[BF crash.txt](https://github.com/bugfender/BugfenderSDK-iOS/files/2782671/BF.crash.txt)

**Comment by RubenVot** [comment]
Thanks a lot for the complete report @r-a-o . We will investigate this issue as soon as possible.

**Comment by jgimenez** [comment]
Fixed in https://github.com/bugfender/BugfenderSDK-iOS/releases/tag/1.6.3

**Comment by r-a-o** [comment]
Hi, looks like the issue still happens on the latest SDK, 1.6.3 

[crash.txt](https://github.com/bugfender/BugfenderSDK-iOS/files/2856123/crash.txt)
