### ISSUE TITLE
Crash in __41-[BFStorageItem sendWithCompletionBlock:]_block_invoke + 296

### ISSUE THREAD

**Issue by jgimenez** [bugfender/BugfenderSDK-iOS#42]
Hi, looks like the issue still happens on the latest SDK, 1.6.3 

[crash.txt](https://github.com/bugfender/BugfenderSDK-iOS/files/2856123/crash.txt)

<img width="1067" alt="crash-screenshot" src="https://user-images.githubusercontent.com/2171268/52691343-9d23c100-2f86-11e9-9efa-5401d96b6cbe.png">

_Originally posted by @r-a-o in https://github.com/bugfender/BugfenderSDK-iOS/issues/41#issuecomment-462769847_

**Comment by jgimenez** [comment]
It looks like the crash.txt and the screenshot do not correspond to the same crash?  They look different

**Comment by r-a-o** [comment]
Here is the right crash log,
[crash_sendLogsForSessionId.txt](https://github.com/bugfender/BugfenderSDK-iOS/files/2863577/crash_sendLogsForSessionId.txt)

**Comment by jgimenez** [comment]
We confirmed in a private conversation that the crash occurred in v1.6.2, which has been already fixed (#41 ).

**Comment by p4checo** [comment]
Hi, 👋 

I'm afraid this is still happening on 1.6.3:

![image](https://user-images.githubusercontent.com/1391324/53412070-3b207e00-39c0-11e9-881a-1b50a184aec1.png)

```
Crashed: NSOperationQueue 0x281f696c0 (QOS: UNSPECIFIED)
0  libobjc.A.dylib                0x219059430 objc_retain + 16
1  BugfenderSDK                   0x105d6ae54 -[BFStorageItem bf_sendLogsForSessionId:batchSize:withCompletionBlock:] (BFStorageItem.m:631)
2  BugfenderSDK                   0x105d69d88 __41-[BFStorageItem sendWithCompletionBlock:]_block_invoke (BFStorageItem.m:449)
3  Foundation                     0x21a9018bc __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
4  Foundation                     0x21a809ab8 -[NSBlockOperation main] + 72
5  Foundation                     0x21a808f8c -[__NSOperationInternal _start:] + 740
6  Foundation                     0x21a903790 __NSOQSchedule_f + 272
7  libdispatch.dylib              0x2198a96c8 _dispatch_call_block_and_release + 24
8  libdispatch.dylib              0x2198aa484 _dispatch_client_callout + 16
9  libdispatch.dylib              0x21984d82c _dispatch_continuation_pop$VARIANT$mp + 412
10 libdispatch.dylib              0x21984cef4 _dispatch_async_redirect_invoke + 600
11 libdispatch.dylib              0x219859a18 _dispatch_root_queue_drain + 376
12 libdispatch.dylib              0x21985a2c0 _dispatch_worker_thread2 + 128
13 libsystem_pthread.dylib        0x219a8d17c _pthread_wqthread + 472
14 libsystem_pthread.dylib        0x219a8fcec start_wqthread + 4
```

Perhaps this should be reopened? Cheers 🍻

**Comment by jgimenez** [comment]
Hi @p4checo, this stacktrace looks like 1.6.2. Please contact us via support so we can research your case, it would be good if you can provide specific Bugfender IDs of the devices where you're experiencing the issue and the full report from Crashlytics.

**Comment by p4checo** [comment]
Hi @jgimenez, 

I'm certain it isn't from 1.6.2, as on our app version that it occurred we had already updated to 1.6.3.

Will open a support chat so that I can share the information you require.

**Comment by r-a-o** [comment]
Hi, Can confirm, this is happening on our latest release which carries BF 1.6.3 sdk.

[Although not as many crashes as 1.6.2]

[crash-BF-1.6.3.txt](https://github.com/bugfender/BugfenderSDK-iOS/files/2905564/crash-BF-1.6.3.txt)

**Comment by jgimenez** [comment]
Hi there, our engineers confirm this issue was actually solved in 1.6.4 instead of 1.6.3. Actually there were two issues that were identified and solved in 1.6.3 and 1.6.4 separately, I'm sorry about the confusion. Upgrading to 1.6.4 should solve the problem.
